language: node_js

node_js:
  - 'stable'
  - '4'
  - '0.10'

sudo: false

matrix:
  fast_finish: true
  include:
  - os: osx
    node_js: stable
    osx_image: xcode7.3

branches:
  only:
  - master
  - transforms
