name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Test the latest version of Node.js plus the last two LTS versions.
        node-version:
          - "*"
          - lts/*
          - lts/-1
          - vscode

    steps:
    - uses: actions/checkout@v3

    - name: Use node version ${{ matrix.node-version }}
      if: ${{ matrix.node-version != "vscode" }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Use VS Code as node
      if: ${{ matrix.node-version == "vscode" }}
      run: |
        node ./scripts/electron-node/download.js
        echo "$PWD/scripts/electron-node/.bin" >> $GITHUB_PATH

    - run:  npm ci

    - name: Tests
      run:  npm test -- --no-lint

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "*"
        check-latest: true
    - run:  npm ci

    - name: Linter
      run:  npm run lint:ci

  browser-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "*"
        check-latest: true
    - run:  npm ci

    - name: Adding playwright
      run: npm install --no-save --no-package-lock playwright

    - name: Build local
      run: gulp local

    - name: Validate the browser can import TypeScript
      run: gulp test-browser-integration
